name: Pull Request CI

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, ready_for_review]

env:
  PYTHON_VERSION: "3.11"

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_agent_broker
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov flake8 black isort

      - name: Code Quality Checks
        run: |
          echo "🔍 Running code quality checks..."
          
          # Format check
          echo "📝 Checking code formatting..."
          black --check app/ || (echo "❌ Code formatting issues found. Run 'black app/' to fix." && exit 1)
          
          # Import sorting
          echo "📦 Checking import sorting..."
          isort --check-only app/ || (echo "❌ Import sorting issues found. Run 'isort app/' to fix." && exit 1)
          
          # Linting
          echo "🔎 Running linting checks..."
          flake8 app/ --max-line-length=88 --extend-ignore=E203,W503 || echo "⚠️ Linting issues found (non-blocking)"

      - name: Security Scan
        run: |
          echo "🛡️ Running security scan..."
          pip install bandit safety
          bandit -r app/ -f json || echo "⚠️ Security issues found (non-blocking)"
          safety check || echo "⚠️ Dependency vulnerabilities found (non-blocking)"

      - name: Run Tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_agent_broker
          SECRET_KEY: test-secret-key-for-pr
          SUPABASE_URL: https://test.supabase.co
          SUPABASE_ANON_KEY: test-anon-key
          ENVIRONMENT: testing
        run: |
          echo "🧪 Running test suite..."
          
          # Basic import tests
          python -c "
          import sys
          sys.path.append('app')
          try:
              from app.main import app
              print('✅ FastAPI app imports successfully')
          except Exception as e:
              print(f'❌ FastAPI import failed: {e}')
              exit(1)
          "
          
          # Run pytest if tests exist
          if [ -d "tests" ]; then
            python -m pytest tests/ -v --tb=short --cov=app --cov-report=xml || echo "⚠️ Some tests failed"
          else
            echo "ℹ️ No tests directory found"
          fi

      - name: Build Test
        run: |
          echo "🏗️ Testing build process..."
          if [ -f "deployment/Dockerfile" ]; then
            docker build -f deployment/Dockerfile -t agent-influence-broker:pr-test . || echo "⚠️ Docker build failed"
          else
            echo "ℹ️ No Dockerfile found"
          fi

      - name: PR Comment Summary
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const { context } = require('@actions/github');
            
            const summary = `## 🔍 Pull Request Validation Summary
            
            ### ✅ Completed Checks:
            - Code formatting (Black)
            - Import sorting (isort) 
            - Linting (flake8)
            - Security scan (Bandit & Safety)
            - Import validation
            - Build test
            
            ### 📊 Results:
            - **Status**: ${{ job.status }}
            - **Python Version**: ${{ env.PYTHON_VERSION }}
            - **Branch**: ${{ github.head_ref }}
            - **Commit**: ${{ github.sha }}
            
            ### 🎯 Next Steps:
            ${job.status === 'success' ? 
              '✅ All checks passed! This PR is ready for code review.' : 
              '⚠️ Some checks failed. Please review the logs and fix any issues.'}
            
            ---
            *Automated check by Agent Influence Broker CI*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });

  auto-merge-dependabot:
    runs-on: ubuntu-latest
    needs: pr-validation
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.state == 'open'
    
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: |
          echo "🤖 Auto-approving Dependabot PR"
          # This would enable auto-merge for dependency updates
          # Requires repository settings to allow auto-merge

  pr-size-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PR size
        uses: actions/github-script@v7
        with:
          script: |
            const { context } = require('@actions/github');
            const pr = context.payload.pull_request;
            
            const additions = pr.additions;
            const deletions = pr.deletions;
            const changedFiles = pr.changed_files;
            
            let size = 'small';
            let emoji = '🟢';
            
            if (additions + deletions > 1000 || changedFiles > 20) {
              size = 'large';
              emoji = '🔴';
            } else if (additions + deletions > 300 || changedFiles > 10) {
              size = 'medium';
              emoji = '🟡';
            }
            
            const comment = `## ${emoji} PR Size: ${size.toUpperCase()}
            
            - **Files changed**: ${changedFiles}
            - **Lines added**: ${additions}
            - **Lines deleted**: ${deletions}
            
            ${size === 'large' ? '⚠️ **Large PR detected!** Consider breaking this into smaller PRs for easier review.' : ''}
            ${size === 'medium' ? 'ℹ️ Medium-sized PR. Should be manageable to review.' : ''}
            ${size === 'small' ? '✅ Small PR - perfect size for quick review!' : ''}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
